### ISSUE TITLE
[Bug]: Failed to load canvas mindmap upon enabling

### ISSUE THREAD

**Issue by devinat1** [Quorafind/Obsidian-Canvas-MindMap#10]
### Bug Description

I am unable to enable the plugin in my vault. It says "failed to load canvas mindmap".

### Obsidian Version

1.1.9

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Can you take a screenshot of CONSOLE when you are failed to enable it? it should be `Ctrl+Shift+i` on windows OR `Command+Option+i` on mac

**Comment by Lohartte** [comment]
> Can you take a screenshot of CONSOLE when you are failed to enable it? it should be `Ctrl+Shift+i` on windows OR `Command+Option+i` on mac

![Failed to load canvas mindmap when ob launched](https://user-images.githubusercontent.com/91640363/209907349-607cf6b2-ac2a-4e3e-9930-000081db59cc.png)
Failed to load canvas mindmap when ob launched

**Comment by Quorafind** [comment]
Fixed, will be released in next version.

**Comment by devinat1** [comment]
When is the next version out?

**Comment by Quorafind** [comment]
@devinat1 fixed in #11
