### ISSUE TITLE
[Bug]: Lost focus after created new node

### ISSUE THREAD

**Issue by Quorafind** [Quorafind/Obsidian-Canvas-MindMap#12]
### Bug Description

Im a little bit confused, beccause the enter/tab functionality does only work once, after that i have to click on another node to switch between nodes or create new ones..

### To Reproduce

1. Focus on a node;
2. Press `tab` or `enter` to created new node;
3. Repro

### Obsidian Version

1.1.9

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by duckfarts** [comment]
After you create a new node, you're then editing it, so hitting Enter doesn't create another node. Hit Esc to exit edit mode, then you can hit Tab or Enter.
