### ISSUE TITLE
Feature Request: several requests, including: possible to add an option to adjust the default width (and height) of the block?

### ISSUE THREAD

**Issue by ghweili** [Quorafind/Obsidian-Canvas-MindMap#13]
### Feature Requested

1. since I usually write long notes in a block which I prefer to display with a larger default width, I wonder if the plugin can provide the option to set the default width?  

2. Besides, would it possible to add another option to choose whether the block uses a fixed height, or if it should change its height to display all the contents within the card?  

3. It could be convenient if one can adjust the width of the block easily. For example, if the plugin provides a hotkey such that  when the user presses the hotkey, the plugin knows that the user want to customize the width of the current block, so that the block continues displaying texts in the same line, then when the user presses the hotkey again, the plugin knows that the users is satisfied with the current block width,  then the plugin sets the width of the current block as the current width. 

Thank you.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Supported, you can set it in settings.
