### ISSUE TITLE
[Bug]: BRAT says "Release is not complete"

### ISSUE THREAD

**Issue by claremacrae** [Quorafind/Obsidian-Canvas-MindMap#18]
### Bug Description

I have this installed via BRAT.
Recently it has started showing this at startup:

![image](https://user-images.githubusercontent.com/4840096/215432298-abc8c258-e245-4240-8534-72aed09bc00c.png)

The last successful install was:

```
[[2023/01/2023-01-11 Wednesday]] 20:45 [machinename].local canvas-mindmap Plugin has been updated
from version 0.1.0 to 0.1.2. [Release Info](https://github.com/Quorafind/obsidian-canvas-mindmap/releases/tag/0.1.2)
```

_(I clicked the 'I have updated to the latest version' checkbox in order to submit the issue - but obviously I didn't actually update, because I couldn't)_

### Relevant Screenshot

See abobe

### Obsidian Version

1.1.12

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by claremacrae** [comment]
I think it might be because the manifest points to 0.1.3 which does not exist:

https://github.com/Quorafind/Obsidian-Canvas-MindMap/blob/bc84ad3f63329bdb0b16c414043d6ec8e4b2a1e1/manifest.json#L4

**Comment by Quorafind** [comment]
> I think it might be because the manifest points to 0.1.3 which does not exist:
> 
> https://github.com/Quorafind/Obsidian-Canvas-MindMap/blob/bc84ad3f63329bdb0b16c414043d6ec8e4b2a1e1/manifest.json#L4

Yes, i will bump version and release it soon.

**Comment by claremacrae** [comment]
> Yes, i will bump version and release it soon.

Ah right. Thanks.

If it isn't on your list already, later on it might be worth setting up a release process that updates all the files with version numbers at the same time.

**Comment by claremacrae** [comment]
> Yes, i will bump version and release it soon.

Not that it matters, but I'm confused, as the link I used showed that the version number had already been bumped..

Anyways - thanks for the reply.

I'll leave this open for now, in case others come here to report the same thing...
