### ISSUE TITLE
[Bug]: Enter does not create a brother node.

### ISSUE THREAD

**Issue by devinat1** [Quorafind/Obsidian-Canvas-MindMap#22]
### Bug Description

When I press tab, a new node will be created as expected as a child of the current card.
However, when I press enter, it just inserts a new line into the current card. This is annoying since I have to continuously click on the card again to press enter and have the expected functionality.

### To Reproduce

Press Enter on any card with the focus on the text (when being able to edit).
Does not work when you are actually able to edit the text in other words.

### Obsidian Version

1.1.9

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
You can press esc and then create a new node by pressing enter. But I can add a hotkey to make this be handled easily.

**Comment by liangzh-404** [comment]
> You can press esc and then create a new node by pressing enter. But I can add a hotkey to make this be handled easily.

not work, need to click somewhere

**Comment by bjornfiles** [comment]
At least give us the option to make Enter/Return always create a sibling node. Please. This plugin simply isn't very useful without a one-key way to create sibling nodes.

**Comment by jacksteamdev** [comment]
This is surprising to me, I expect a UX similar to Ayoa: 

```
Enter -> New sibling
Tab -> New child
```

I find multiline cards counterintuitive, I expect `Shift+Enter` to create a new line in a card.

I realize this would be a "breaking change" for this plugin... not sure what the solution is, aside from forking the extension and changing the behavior... 😭

**Comment by Quorafind** [comment]
Now you can set hotkey to call this feature globally.
