### ISSUE TITLE
[Bug]: When creating too many cards, these cards overlap with each other.

### ISSUE THREAD

**Issue by devinat1** [Quorafind/Obsidian-Canvas-MindMap#23]
### Bug Description

When I am creating many cards using this plugin, the cards don't utilize space efficiently. In fact, past 3 cards, I have to manually move the branches, which makes for an annoying experience. 
The branches should move and auto-format based on the location of the branches.

### Relevant Screenshot

Me having to manually move the cards to make the plugin work:
![image](https://user-images.githubusercontent.com/15788108/218333520-954ff260-bc95-4761-89e7-e7a2ded74d17.png)
Notice how I had to drag down the child cards.

### To Reproduce

Create many brother and child cards via tab and enter, and this will happen.

### Obsidian Version

1.1.9

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
It is hard and low performance to calculate a new node and other existed node when in larage canvas. But I will make some change to this soon.

**Comment by Quorafind** [comment]
Supported auto layout.
