### ISSUE TITLE
Feature Request: new node direction setup?

### ISSUE THREAD

**Issue by atnoir** [Quorafind/Obsidian-Canvas-MindMap#24]
### Feature Requested

When creating a brother card or child card, I find it always follows the left-right direction. Usually, I prefer to build a mindmap from top to bottom, and therefore this "enter" and "tab" shortcuts are more hassle because I need to drag the node every time to make it into the direction I want.

My question/feature is: is there some setup to do this, for I don't see a gear icon for this plug-in? if not, would you like to add such a feature?

Many thanks. 

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Will be add soon.

**Comment by atnoir** [comment]
> Will be add soon.

thank you so much!

**Comment by MartinBernstorff** [comment]
Hi @Quorafind! Thanks a tonne for your OSS work, this is awesome! I'm considering setting up a workflow centered around this request; do you know if it's forthcoming? :-)

**Comment by Quorafind** [comment]
Supported.
