### ISSUE TITLE
[Bug]: "Tab" shortcut resulting in conflict with "Indent"

### ISSUE THREAD

**Issue by atnoir** [Quorafind/Obsidian-Canvas-MindMap#25]
### Bug Description

"Tab" is commonly used in outliner as "indent line", and this mindmap addon doesn't support other hotkey configurations for creating the child card. Both provide zero customization and so I have to disable this addon. Hoping for a solution. Thanks.

### To Reproduce

1. open a new canvas;
2. create a new card;
3. enter the edit mode of that card and try to indent a line with "tab";
4. but that "tab" only leads to an unwanted new child card.

### Obsidian Version

1.1.9

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by duckfarts** [comment]
I have the same problem.

I'd prefer this to work like how Enter works now, where Tab only creates a new card if you're not currently editing it.

**Comment by Quorafind** [comment]
Will be fix soon.

**Comment by atnoir** [comment]
> I have the same problem.
> 
> I'd prefer this to work like how Enter works now, where Tab only creates a new card if you're not currently editing it.

I agree, and that sounds like the best solution. 👍

**Comment by hongxunming** [comment]
You can try the following methods to fix this issue:

#1. Open this file: Your_Obsidian_Vault_File_Path/.obsidian/plugins/canvas-mindmap/main.js
 • Note: On a MacBook, if you can't see ".obsidian" file in the Obsidian vault folder, please use "Command + Shift + ." to view hidden files.

#2. Modify the code using either of the two ways below:
Method 1:** Go to line 358 and add the following code below that line:
      if (parentNode.isEditing)
        return;

Remember to save!

Method 2: You can also search for "const parentNode = canvas.selection" (on line 358), and then add the following code below it:
      if (parentNode.isEditing)
        return;

Remember to save!

<img width="656" alt="image" src="https://github.com/Quorafind/Obsidian-Canvas-MindMap/assets/43163254/d6074b78-ec71-420f-99e6-bd67174d6605">


#3. Check if the Canvas Mindmap is now functioning properly. If it's not, restart Obsidian and try again.

**Comment by BL1133** [comment]
> Will be fix soon.

I wish this was fixed. I don't know how it isn't driving everyone crazy to not be able to use tab inside of a card.

**Comment by Lisandra-dev** [comment]
@Quorafind Do you think you will fix this issue ? It drives me mad and I don't want to disable the plugin, as it is very usefull :(

**Comment by Quorafind** [comment]
got fixed
