### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by XuanNui** [Quorafind/Obsidian-Canvas-MindMap#27]
### Feature Requested

Function suggestions:
1 Can there be a setting to adjust the distance of the card arrow
2 Can there be an up and down direction for the mind map

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/104402409/218923089-54fb5214-cac1-45cd-b118-0a0496ab226c.png)
![image](https://user-images.githubusercontent.com/104402409/218923235-fc1711e5-baa7-484e-8874-6045f432e434.png)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Supported in settings, all changes would take affect when you create next node.
