### ISSUE TITLE
[Bug]: Plugin keeps updating even though there are no updates

### ISSUE THREAD

**Issue by devinat1** [Quorafind/Obsidian-Canvas-MindMap#28]
### Bug Description

Every time I open up obsidian. it says there is an update available, then I update.
The last version of obsidian canvas mindmap was 3 weeks ago, so I don't know why it keeps asking for updates where there aren't any present.

### To Reproduce

1. Open obsidian
2. Click check updates
3. Shows there is an update available when there isn't!

### Obsidian Version

1.1.9

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Could you tell me the version number of this plugin in Obsidian? Is it 0.1.3 or 0.1.4?

**Comment by Quorafind** [comment]
Fixed
