### ISSUE TITLE
[Bug]: I cannot create brother or child nodes

### ISSUE THREAD

**Issue by j-fuentes** [Quorafind/Obsidian-Canvas-MindMap#29]
### Bug Description

I have installed the plugin, enabled it and restarted obsidian.

But I cannot get the plugin to create brother or sibling cards.

### To Reproduce

I click on a node, then click `Enter` but nothing happens.
If I click `Tab` the buttons above the node are highlighted.

![image](https://user-images.githubusercontent.com/10594577/226583581-194751be-44ce-4224-a81d-db82d5527b3f.png) 

### Obsidian Version

0.1.3

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by j-fuentes** [comment]
I have learned you can open a console in obsidian. This is the output of it when in a new canvas, I add a node, press `esc` and then `Enter`:

![image](https://user-images.githubusercontent.com/10594577/226587655-2e61fd2e-9194-4daa-8722-fd807e7b2fa1.png)

**Comment by j-fuentes** [comment]
I have noticed this:

- I can create a child with `Alt` and from there I can create brothers.


I was trying to create brothers for a node without a parent, 🤦🏽 .

So the plugin is doing what it is supposed to do, the problem was between screen and keyboard.

**Comment by j-fuentes** [comment]
I am reopening because I have noticed it happens sometimes. I select a node, I click `tab` and it does nothing but highlighting the bin icon.

**Comment by j-fuentes** [comment]
Also, I hit `Ctrl` + `arrow right` and it does not create a floating node. Seems like the plugin is not active, but it is there.

I have tried to disable and enable this but it didn't work.

**Comment by BL1133** [comment]
> ### Bug Description
> I have installed the plugin, enabled it and restarted obsidian.
> 
> But I cannot get the plugin to create brother or sibling cards.
> 
> ### Relevant Screenshot
> _No response_
> 
> ### To Reproduce
> I click on a node, then click `Enter` but nothing happens. If I click `Tab` the buttons above the node are highlighted.
> 
> ![image](https://user-images.githubusercontent.com/10594577/226583581-194751be-44ce-4224-a81d-db82d5527b3f.png)
> 
> ### Obsidian Version
> 0.1.3
> 
> ### Checklist
> * [x]  I updated to the latest version of the plugin.

Same thing with me. When I looked it up I found what the problem is. You have to reinstall it from the Obsidian website. The installer is different from Obsidian updating itself. When I ran the installer, My icon changed and now all plugins work.

**Comment by Quorafind** [comment]
Fixed.
