### ISSUE TITLE
[Bug]: Alt-arrow hotkey conflicts with text navigation hotkey in edit mode

### ISSUE THREAD

**Issue by rpggio** [Quorafind/Obsidian-Canvas-MindMap#30]
### Bug Description

When editing text, I use alt-arrow to skip to word boundaries. This is a generally universal hotkey. This conflicts with canvas MindMap note navigation hotkey.
This could be fixed by ignoring the hotkey when a note is in edit mode. This would allow the editing mode hotkey to operate properly.

### Obsidian Version

1.1.16

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by xyw0025** [comment]
I guess a quick workaround is to change the binding keys in `main.js` to what you prefer and [manually install the plugin.](https://github.com/Quorafind/Obsidian-Canvas-MindMap#download-manually)

thier main.js in [release 0.1.3](https://github.com/Quorafind/Obsidian-Canvas-MindMap/releases/tag/0.1.3):
```javascript
const canvasViewunistaller = around(canvasView.constructor.prototype, {
  onOpen: (next) =>
    async function () {
      # ...
      this.scope.register(['Alt'], 'ArrowUp', () => {
          navigate(this.canvas, 'top');
        });
      # also change other lines you have issues with
```
I changed it to the following:

```javascript
const canvasViewunistaller = around(canvasView.constructor.prototype, {
  onOpen: (next) =>
    async function () {
      # ...
      this.scope.register(['Alt', 'Shift'], 'ArrowUp', () => {
          navigate(this.canvas, 'top');
        });
       # ...
```

**Comment by Quorafind** [comment]
fixed.
