### ISSUE TITLE
Feature Request: Automaticly layout

### ISSUE THREAD

**Issue by Juan-hwt** [Quorafind/Obsidian-Canvas-MindMap#31]
### Feature Requested

I like the function of mindmap, so I think it is better that if the obsidian can repalce mindmao.
now if the canvas have too many nodes, it is difficult to re-arrange all.

so, if the plugin have the function that **one-key-automaticly-layout**, re-organize all the nodes,
the work will be more convenient and quickly

thank you

### Checklist

- [ ] The feature would be useful to more users than just me.

**Comment by 3spo14** [comment]
I agree!

**Comment by Quorafind** [comment]
Supported.
