### ISSUE TITLE
Feature Request: Custom hotkeys

### ISSUE THREAD

**Issue by daamiian** [Quorafind/Obsidian-Canvas-MindMap#32]
### Feature Requested

Tab and enter conflict with a lot of functions in Obsidian, at least for my vault. 

I think being able to set all of the shortcuts to whatever the user needs is essential. 

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by syrom** [comment]
Second that ! ENTER actually doesn't work for me, but TAB does to create a child note.

**Comment by Quorafind** [comment]
Now it won't conflict when you are editing. and you can set hotkey for these two commands.
