### ISSUE TITLE
Feature Request: How can I disabled floating cards

### ISSUE THREAD

**Issue by shaunhurryup** [Quorafind/Obsidian-Canvas-MindMap#33]
### Feature Requested

Thanks for your Canvas Mindmap, it helps me a lot in taking notes, and almost exactly what I want.

The one thing is that

> Press Cmd / Ctrl + ←/→/↓/↑ to create floating cards;

The keyboard `cmd` is usually used to move the cursor to the end or start with the front and back keys.

My guess is that some plugins support custom or diable shortcuts, but I didn't find in Canvas Mindmap.

### Checklist

- [x] The feature would be useful to more users than just me.

**Comment by MathiasGronseth** [comment]
As a super temporary fix, you can go into .obsidian\plugins\canvas-mindmap\main.js and find line 466 and comment out the following: 
`const canvasViewunistaller = around(canvasView.constructor.prototype, {
        onOpen: (next) => async function() {
          // this.scope.register(["Mod"], "ArrowUp", () => {
          //   createSperateNode(this.canvas, "top");
          // });
          // this.scope.register(["Mod"], "ArrowDown", () => {
          //   createSperateNode(this.canvas, "bottom");
          // });
          // this.scope.register(["Mod"], "ArrowLeft", () => {
          //   createSperateNode(this.canvas, "left");
          // });
          // this.scope.register(["Mod"], "ArrowRight", () => {
          //   createSperateNode(this.canvas, "right");
          // });`
This is a *very* temporary fix though. This file gets auto generated and will be overwritten at some point. I just got very frustrated with it as I constantly skip words by using Ctrl + Left/Right

**Comment by PeterMilovcik** [comment]
@MathiasGronseth: Thanks a lot for the workaround. It works.

However, I would highly welcome the proper solution. Please, make that as an option in the settings, or hotkey override, or just remove the floating cards (I have not found a use for them). It is indeed, very annoying as a user of Ctrl+ Left/Right for navigating the words.

**Comment by Quorafind** [comment]
Supported
