### ISSUE TITLE
Feature Request: 可以实现command/control+enter/tab功能吗?

### ISSUE THREAD

**Issue by qwepuorytgj** [Quorafind/Obsidian-Canvas-MindMap#34]
### Feature Requested

插件目前的功能:
Press Enter to create brother card
Press Tab to create child card
但如果已经在卡片里编辑了,就需要点击白板的其他地方退出编辑,再点击到对应的卡片,按Enter/Tab建立同级/下级
可不可以在编辑卡片的过程中,当这个卡片编辑完之后,直接按command+Enter/Tab建立同级/下级?

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
已支持定义 Obsidian 全局的快捷键。注意，Ctrl+Enter 此前也是完成复选框的快捷键。
