### ISSUE TITLE
Feature Request: Tab + Arrow Key to Control Position of Child

### ISSUE THREAD

**Issue by Bluemoondragon07** [Quorafind/Obsidian-Canvas-MindMap#35]
### Feature Requested

Thank you so much for this plugin! It's really useful for taking notes at school. 

The feature I propose is a new function: `TAB` + `←/→/↓/↑` to choose the position of a new child card. 

Right now, `Cmd / Ctrl` + `←/→/↓/↑` will create floating cards, but I think it would be even better if similar controls could be applied to child cards.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Now you can use mod+shift+arrow to create child node, and change the mindmap direction at the same time.

Using `Tab` with arrow key is not a robust way to do so. Because it need to listen to any tab key press event.
