### ISSUE TITLE
[Bug]: Unable to delete card 

### ISSUE THREAD

**Issue by trileobayu** [Quorafind/Obsidian-Canvas-MindMap#38]
### Bug Description

when i Enable the plugin. I cant use Del key to delete any card, page, or media. 
But i still can use the alternative SHIFT + Del to delete them. it is very inconvenient 
Additionally, it cant delete 1 card. But if i select more than 1 card, the del key works properly.

### Obsidian Version

1.4.14

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Would be fixed in next version.
