### ISSUE TITLE
[Bug]: plugin doesn't work on Obsidian v1.4.16

### ISSUE THREAD

**Issue by vramULB** [Quorafind/Obsidian-Canvas-MindMap#41]
### Bug Description

Hotkeys/shotcuts no longer work after updating to the 1.4.16 version.

I tried to reinstall plugin without success.

### To Reproduce

1. Update obsidian to version 1.4.16
2. Open canvas 

### Obsidian Version

1.4.16

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Interesting, it is still working well on my end. Could you provide more info like plugins you enabled.
