### ISSUE TITLE
Feature Request: shortcut to edit note

### ISSUE THREAD

**Issue by j-fuentes** [Quorafind/Obsidian-Canvas-MindMap#42]
### Feature Requested

It would be great to have a shortcut that edits the current node.

Use case:
I am navigating the nodes with my keyboard using the `Alt` + `arrows` shortcut. I want to edit a node and I don't know how to do it without having to reach to the mouse.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Now ti support using `space` to focus and editing current node.
