### ISSUE TITLE
Feature Request:  Vertical Mode Switch

### ISSUE THREAD

**Issue by SiameseParrots** [Quorafind/Obsidian-Canvas-MindMap#43]
### Feature Requested

 - Adding an option inside plugin-setting to switch between vertical & horizontal (default) mode. 

Thank You for sharing this awesome plugin with us, appreciating your minimalistic flow !

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
You can set it in settings/commands/status bar, or just hotkeys.
