### ISSUE TITLE
Feature Request: enable plugin on per-canvas basis

### ISSUE THREAD

**Issue by jimjam-slam** [Quorafind/Obsidian-Canvas-MindMap#46]
### Feature Requested

This is a great plugin! It'd be great if it could be toggled on and off without going into settings—and, even better, if there was memory for this toggle's state on a per-canvas basis.

There are times when I (and, I think, others) want to use canvas as a mindmap and times when I don't, but since the plugin changes the layout automatically, it would be easy to accidentally change the layout of a canvas if I leave the plugin on.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by brahov** [comment]
I agree. This would be very nice. I use Canvas a lot and this could mess up my existing layouts!

**Comment by Quorafind** [comment]
Now you can disabled the autolayout and open it again when you need it. Or just change its direction when you don't want it.
