### ISSUE TITLE
[Bug]: Nondeterministic behavior of tab key

### ISSUE THREAD

**Issue by devinat1** [Quorafind/Obsidian-Canvas-MindMap#48]
### Bug Description

When I click tab, sometimes a new card is created in which the text input shows up, and sometimes it creates a card but does not show text (so the card is selected but not in text input mode). I would ideally like it so that I can press tab to create a new card and the text input shows up when I click a hotkey on that card (so pressing alt + I to open the text mode in that card for example). Otherwise it is annoying having to click on the card again with my mouse some of the time every time I create a new card via the tab key
Note that ctrl up down etc. doesn't have this issue, and enter key does have the issue.

### Relevant Screenshot

SYSTEM INFO:
	Obsidian version: v1.5.8
	Installer version: v1.4.16
	Operating system: Windows 10 Home 10.0.26058
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.5.2
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 56
	Plugins enabled: 12
		1: Templater v2.2.3
		2: Ghost Fade Focus v3.0.0
		3: Tab Switcher v1.4.0
		4: Google Photos v1.6.5
		5: Dataview v0.5.64
		6: Editor Syntax Highlight v0.1.3
		7: Minimal Theme Settings v7.3.1
		8: Commander v0.5.1
		9: Quick Switcher++ v4.0.0
		10: Canvas Mindmap v0.1.9
		11: Auto Link Title v1.5.3
		12: Admonition v10.2.0

### To Reproduce

Press tab or enter

### Obsidian Version

v1.5.8

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by brahov** [comment]
The same goes for Enter. I've created a separate Bug for this.

**Comment by itsonlyjames** [comment]
Press space to enter edit mode. I made some code adjustments so I can use enter to edit, and cmd+enter to finish editing (similar to excalidraw). I'm going to either make a PR for this repo, or fork and make some improvements should the author no longer maintain this.

**Comment by devinat1** [comment]
Thanks that would be quite useful!

**Comment by Quorafind** [comment]
Fixed. You can set it in settings
