### ISSUE TITLE
[Bug]: ENTER jumping into card and not adding a child

### ISSUE THREAD

**Issue by brahov** [Quorafind/Obsidian-Canvas-MindMap#49]
### Bug Description

In some cases (not entirely clear which ones yet) using `Enter` doesn't result in the child card but jumps me into a card or file. After hitting `Esc` it will sometimes resume working, and at other times it won't until I've selected something else with the mouse cursor.

### Relevant Screenshot

![image](https://github.com/Quorafind/Obsidian-Canvas-MindMap/assets/156023424/93c678d3-41ba-47bf-b11b-f509e8f2529d)

### To Reproduce

- Create new canvas
- Create card
- Create brother or child
- Create several children in a row
- Selection enters random card

### Obsidian Version

1.5.8

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by felixqueisler** [comment]
If this is simply due to an overlap of keybindings: Change Plugin to use CMD+Enter for a new node.

**Comment by Quorafind** [comment]
Fixed.
