### ISSUE TITLE
[Bug]:  Unable to delete the first note with [backspace] key

### ISSUE THREAD

**Issue by vecyang1** [Quorafind/Obsidian-Canvas-MindMap#50]
### Bug Description

Though for child cars it works, currently It's' unable to delete the first note with [backspace] key. (seems a sort of protection)

While this is not what I want. I use it as a canva instead of a mindmap. I have several cards as start point. If it can't delete with [backspace], I have to mannually select and click to delete.

The plugin is really useful. May I know how could I overcome this?

### Obsidian Version

About Obsidian Version 1.5.11 (Installer 1.5.11)

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by ipv6sq** [comment]
same here

**Comment by itsonlyjames** [comment]
Entirely related to [this line here](https://github.com/Quorafind/Obsidian-Canvas-MindMap/blob/a852e08bd25c0e8e6ab10fcc5fdd4edcc472881e/src/canvasMindMap.ts#L456)

I don't think it's correct, that it hijacks backspace and prevents it if there are 0 edges. That will be why you/we can't delete the first node. 

Tbh, the auto layout doesn't even work for me? So a setting to turn off this off would be ideal. For now, just edit `canvas-mindmap/main.js` lines 753–815 and either delete or comment them out. Reload Obsidian. Problem solved. 

Obviously any future updates will overwrite this manual change.

**Comment by Quorafind** [comment]
Fixed.
