### ISSUE TITLE
Feature Request: Hotkey to enter a node & navigate at the same time with the keyboard

### ISSUE THREAD

**Issue by 20112m** [Quorafind/Obsidian-Canvas-MindMap#51]
### Feature Requested

how to use the keyboard to enter into a node to type and then exit to navigate and enter another node and so on? 

I can use the keyboard to navigate but to enter a node I must double click with the mouse. Could there be a hotkey to enter a node?

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by itsonlyjames** [comment]
This plugin uses space by default to enter editing mode. I adjusted the code for myself to make it enter to edit, I'm thinking about opening a PR to make it a setting. I think enter, and cmd+enter makes more sense for keyboard editing—at least coming from excalidraw

**Comment by Quorafind** [comment]
Fixed. You can set it in settings.
