### ISSUE TITLE
[Bug]: layout is broken

### ISSUE THREAD

**Issue by FreePhoenix888** [Quorafind/Obsidian-Canvas-MindMap#54]
### Bug Description

When I create child note it appear above another child note

### Relevant Screenshot

https://github.com/Quorafind/Obsidian-Canvas-MindMap/assets/66206278/69deb979-764c-4898-ae5f-ffe8a9b9a462

### To Reproduce

1. Create note with content `Go`
2. Create child note of `Go` with content `Pros and cons`
3. Create child note of `Pros and cons` with content `Cons`
4. Create child note of `Cons` with content
```
![[shapes_48dp_FILL0_wght400_GRAD0_opsz48.svg|300]]
No generics until 1.18
\`\`\`go
func sum(numbers []interface{}) interface{} {
    var result int
    for _, number := range numbers {
        result += number.(int)
    }
    return result
}
\`\`\`
```
Note: I backslashed \` symbols here
Image:
![shapes_48dp_FILL0_wght400_GRAD0_opsz48](https://github.com/Quorafind/Obsidian-Canvas-MindMap/assets/66206278/f7671b98-7e3e-4c65-9992-88ae8ad3e4eb)
5. Create child note of `Cons` with content
```
![[barefoot_48dp_FILL0_wght400_GRAD0_opsz48 (1) 1.svg|300]]
Too minimalistic std library compared to other languages like python. For example there are no balanced trees and queses with priorities
```
Image: 
![barefoot_48dp_FILL0_wght400_GRAD0_opsz48 (1)](https://github.com/Quorafind/Obsidian-Canvas-MindMap/assets/66206278/90f9995e-418c-495e-a3f3-71cdc2a698d1)
5. Create child note of `Pros and cons` with content `Pros`
6. Create child note of `Pros` and see that it is created above child notes of `Cons`

### Obsidian Version

1.6.5

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by jspkay** [comment]
I have a very similar problem. Canvas is useless right now...

**Comment by Quorafind** [comment]
Fixed.

**Comment by FreePhoenix888** [comment]
> Fixed.

Thank you for your time!
