### ISSUE TITLE
[Bug]: None of the hotkeys are working

### ISSUE THREAD

**Issue by pharan** [Quorafind/Obsidian-Canvas-MindMap#55]
### Bug Description

I just installed the plugin from https://obsidian.md/plugins.
I enabled it.

None of the hotkeys and features are working.
❌ spacebar to edit card
❌ enter to create sibling card
❌ delete card to rearrange
❌ alt arrow keys to navigate

### Relevant Screenshot

![image](https://github.com/Quorafind/Obsidian-Canvas-MindMap/assets/1911082/40ba0803-3962-4260-9a7d-481518d47d3f)
By default, these hotkeys are not set.
But even if they are, they are not complete. Navigate and edit card are not there, and the other features are not hotkeys.

### Obsidian Version

1.6.5

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Fixed.
