### ISSUE TITLE
Feature Request: 操作连贯性有待提升

### ISSUE THREAD

**Issue by niuyongjie** [Quorafind/Obsidian-Canvas-MindMap#9]
### Feature Requested

目前的操作是：
如果想创建节点 A 的子节点或者同级节点，必须先点击空白的地方，再点击 A 节点，然后用快捷键创建节点。在编辑完内容后，想继续创建节点，就得鼠标点击空白的地方，再点击刚才的节点，继续创建。由于鼠标的点击动作，使得操作不连贯。期望可以改进这一点。

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
你可以用 Esc 来退出当前的编辑，然后继续

**Comment by niuyongjie** [comment]
我试了最新的代码，确实可以了
